# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master, workflows ]
  pull_request:
    branches: [ master, workflows ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
      -
        name: "Fetching Materials"
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      -
        env:
          API: "${{ secrets.TG_BOT_API }}"
        name: Construction
        run: |
           DATE="`date +%d%m%Y-%H%M%S`"
           curl -s -X POST "https://api.telegram.org/bot${API}/sendMessage" -d chat_id="-1001365210159" \
              -d "disable_web_page_preview=true" \
              -d "parse_mode=html" \
              -d text="⚒️ <b>Building with HEAD as $(echo $GITHUB_SHA | cut -c1-8)</b> ⚒️"
           ./gradlew assembleDebug

           if [ -f app/build/outputs/apk/debug/app-debug.apk ]; then
              cp app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/TweaksKM-debug-${DATE}.apk
              cd app/build/outputs/apk/debug
              APK=$(echo TweaksKM-debug-*.apk)
              curl --progress-bar -F document=@"${APK}" "https://api.telegram.org/bot${API}/sendDocument" \
                -F chat_id="-1001365210159"  \
                -F "disable_web_page_preview=true" \
                -F "parse_mode=html" \
                -F caption="⭕️ <b>CI build completed successfully!</b>"
              rm -rf app/build/outputs/apk
            else
                curl -s -X POST "https://api.telegram.org/bot${API}/sendMessage" -d chat_id="-1001365210159" \
                     -d "disable_web_page_preview=true" \
                     -d "parse_mode=html" \
                     -d text="❌ <b>Build error, exiting now!</b>"
           fi
